import type { Character, CharacterId } from '../../shared/types'

// フロントエンド用のキャラクターデータ（サーバーのデータを複製）
export const CHARACTERS: Record<CharacterId, Character> = {
  factory_manager: {
    id: 'factory_manager',
    displayName: '工場長 村上 克己',
    role: '工場長',
    firstName: '村上 克己',
    age: 55,
    catchphrase: '言い訳はいい、どうするんだ',
    personality: '現場叩き上げ35年の職人気質',
    avatarColor: '#dc2626',
    relationshipDefault: 50,
  },
  dept_manager: {
    id: 'dept_manager',
    displayName: '製造部長 橋本 賢二',
    role: '製造部長',
    firstName: '橋本 賢二',
    age: 48,
    catchphrase: 'で、コストへの影響は？',
    personality: 'KPIとコスト管理にしか興味がない',
    avatarColor: '#7c3aed',
    relationshipDefault: 60,
  },
  sales: {
    id: 'sales',
    displayName: '営業主任 西村 大輔',
    role: '営業主任',
    firstName: '西村 大輔',
    age: 38,
    catchphrase: 'お客様がそう言ってるんで、あとはよろしくです',
    personality: '顧客との関係維持が最優先',
    avatarColor: '#0891b2',
    relationshipDefault: 55,
  },
  workshop: {
    id: 'workshop',
    displayName: '製造職長 谷口 正',
    role: '製造職長',
    firstName: '谷口 正',
    age: 52,
    catchphrase: 'そんな計画、現場では無理ですよ',
    personality: '35年選手。現場の生き字引',
    avatarColor: '#b45309',
    relationshipDefault: 60,
  },
  procurement: {
    id: 'procurement',
    displayName: '調達担当 木村 隆',
    role: '調達担当',
    firstName: '木村 隆',
    age: 41,
    catchphrase: '今から発注して、納期は保証できませんよ',
    personality: 'リードタイムの現実を一番知っている',
    avatarColor: '#15803d',
    relationshipDefault: 65,
  },
  subcontractor: {
    id: 'subcontractor',
    displayName: '外注先社長 坂本 義雄',
    role: '外注先社長',
    firstName: '坂本 義雄',
    age: 57,
    catchphrase: 'うちのことも考えてくださいよ',
    personality: '町工場の二代目。技術力は高いがキャパに限界',
    avatarColor: '#0369a1',
    relationshipDefault: 70,
  },
  subordinate1: {
    id: 'subordinate1',
    displayName: '部下 田中 美咲',
    role: '生産管理担当（2年目）',
    firstName: '田中 美咲',
    age: 26,
    catchphrase: '確認してきます！',
    personality: '真面目で動きは速い。伝達精度は高い',
    avatarColor: '#be185d',
    relationshipDefault: 80,
  },
  subordinate2: {
    id: 'subordinate2',
    displayName: '部下 佐々木 健太',
    role: '生産管理担当（5年目）',
    firstName: '佐々木 健太',
    age: 31,
    catchphrase: 'あ、そこは自分で判断しちゃいました',
    personality: '経験があるぶん応用が利くが自己流になりやすい',
    avatarColor: '#0284c7',
    relationshipDefault: 75,
  },
  system: {
    id: 'system',
    displayName: 'システム',
    role: 'システム',
    firstName: 'システム',
    age: 0,
    catchphrase: '',
    personality: 'ゲームシステムからの通知',
    avatarColor: '#475569',
    relationshipDefault: 100,
  },
}
